version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
    deploy:
      mode: replicated
      replicas: ${SCALING_FACTOR}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  sqlite:
    image: sqlite:latest
    volumes:
      - db-data:/data
    restart: always

volumes:
  db-data: